# Generated by Django 4.2.10 on 2024-02-16 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxy_data',
            name='uptime',
            field=models.FloatField(),
        ),
    ]
